Add statique materialized view
MTES-MCT/qualicharge pull request #305
Opened 2024-12-18 18:31 UTC by jmaupetit

## Purpose

Having a SQL materialized view for "statique" data would ease recurrent database queries joining the same tables frequently. Moreover this should speed up database queries and response time for API endpoints using them.

## Proposal

- [x] add `sqlalchemy_utils` dependency to ease materialized view management
- [ ] add `statique` materialized view
- [ ] test the materialized view
- [ ] integrate a refresh strategy

2025-01-24 17:07 UTC, jmaupetit commented on src/api/qualicharge/schemas/core.py
> +            ).label("coordonneesXY"),
I've finally found a way to make this column an indexed Geometry.

2025-01-25 08:59 UTC, loco-philippe requested changes
It might be interesting to add two fields: 
- pointdecharge.id
- pointdecharge.updated_at

`Id` is usefull if we need to join materialized view with `session` or `status` table. 
`updated_at` is usefull to filter data (if a query is more complex, we can join data with `pointdecharge` table with `id` field.
For operators, these attributes can be used to check the correspondence of the data with their data.

2025-01-26 23:36 UTC, loco-philippe commented
> It might be interesting to add two fields:
> 
> * pointdecharge.id
> * pointdecharge.updated_at
> 
> `Id` is usefull if we need to join materialized view with `session` or `status` table. `updated_at` is usefull to filter data (if a query is more complex, we can join data with `pointdecharge` table with `id` field. For operators, these attributes can be used to check the correspondence of the data with their data.

To be complete, it will be interesting (filtering) to have the associated codes : 
- code_unit
- code_city
- code_department
- code_region

2025-01-27 11:36 UTC, jmaupetit commented
> > It might be interesting to add two fields:
> > 
> > * pointdecharge.id
> > * pointdecharge.updated_at
> > 
> > `Id` is usefull if we need to join materialized view with `session` or `status` table. `updated_at` is usefull to filter data (if a query is more complex, we can join data with `pointdecharge` table with `id` field. For operators, these attributes can be used to check the correspondence of the data with their data.
> 
> To be complete, it will be interesting (filtering) to have the associated codes :
> 
>     * code_unit
> 
>     * code_city
> 
>     * code_department
> 
>     * code_region

As discussed IRL, we've decided to postpone this (if required) in a later PR. The `code_insee_commune` field should be required first.

2025-01-27 12:15 UTC, loco-philippe approved these changes

2025-01-27 13:47 UTC, merged